eCommerce/cart/urls.py
from django.urls import path
from cart import views

app_name = "cart"

urlpatterns = [
    path('', views.cart, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('change/<int:item_id>/', views.change_item_quantity, name='change_item_quantity'),

    path('confirm-order/', views.confirm_order, name='confirm_order'),
    path('order-confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
]

eCommerce/eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls')),
    path("users/", include("users.urls")),
    path("cart/", include("cart.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eCommerce/home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.index, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about-us/', views.about, name='about-us'),
]

eCommerce/users/urls.py
from django.urls import path
from users import views

app_name = "users"

urlpatterns = [
    path('', views.index, name='home'),
    path('register/', views.registration.as_view(), name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

eCommerce/home/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(null=False)
    message = models.TextField()

    def __str__(self):
        return f"Message from {self.name}"

eCommerce/products/models.py
from django.db import models
from django.contrib.auth import get_user_model
import os

User = get_user_model()

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True,
                            help_text='Enter the category name')
    slug = models.SlugField(max_length=255, unique=True,
                            help_text='A unique slug for the category (no spaces or special characters)')
    description = models.TextField(blank=True,
                                   help_text='Optional description of the category')
    is_active = models.BooleanField(default=True,
                                    help_text='Uncheck to deactivate the category')
    created_at = models.DateTimeField(auto_now_add=True,
                                      help_text='The date and time this category is created')
    updated_at = models.DateTimeField(auto_now=True,
                                      help_text='The date and time this category is updated')
    image = models.ImageField(upload_to='category_images', blank=True,
                              null=True,
                              help_text='Optional image for the category')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children',
                               blank=True, null=True,
                               help_text='Select a parent category, if applicable')

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ['name']

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=255,
                            help_text='Enter the Tag name')
    slug = models.SlugField(max_length=255, unique=True,
                            help_text='A unique slug for the Tag (no spaces or special characters)')
    created_at = models.DateTimeField(auto_now_add=True,
                                      help_text='The date and time this tag is created')
    updated_at = models.DateTimeField(auto_now=True,
                                      help_text='The date and time this tag is updated')
    
    class Meta:
        verbose_name_plural = 'tags'
        ordering = ['name']

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=255,
                            help_text='Enter the product name')
    description = models.TextField(blank=True,
                                   help_text='Provide a detailed description of the product')
    price = models.DecimalField(max_digits=8,
                                decimal_places=2, help_text='Enter the product price')
    created_at = models.DateTimeField(auto_now_add=True,
                                      help_text='The date and time this category is created')
    updated_at = models.DateTimeField(auto_now=True,
                                      help_text='The date and time this category is updated')
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE,
                                 help_text='Select the product category')
    tags = models.ManyToManyField(Tag, related_name='products', blank=True,
                                  help_text='Select the relevant tags for this product')
    available = models.BooleanField(default=True,
                                    help_text='Uncheck if the product is currently unavailable')
    sku = models.CharField(max_length=50, unique=True,
                           help_text='Enter the unique Stock-Keeping Unit (SKU) for the product')
    brand = models.CharField(max_length=100, blank=True,
                             help_text='Enter the brand name of the product')
    image = models.ImageField(upload_to='product_images', blank=True, null=True,
                              help_text='Upload an image for the product',
                              default=os.path.join('static/assets/imgs/shop', 'product-solar-1-2.png'))
    weight = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True,
                                 help_text='Enter the product weight in kilograms (optional)')
    dimensions = models.CharField(max_length=100, blank=True,
                                  help_text='Enter the product dimensions (e.g., 10x20x30 cm)')
    stock_quantity = models.PositiveIntegerField(default=0,
                                                 help_text='Enter the current stock quantity of the product')
    featured = models.BooleanField(default=False,
                                   help_text='Check to mark this product as featured')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'products'
        ordering = ['-created_at']

class Review(models.Model):
    author = models.ForeignKey(User, related_name='reviews', on_delete=models.CASCADE,
                             help_text='User submitting the review')
    content = models.TextField(help_text='Provide your thoughts about the product here')
    product = models.ForeignKey(Product, related_name='products', on_delete=models.CASCADE,
                                help_text='Select the product for reviewing')
    created_at = models.DateField(auto_now_add=True,
                                  help_text='The date and time this review is created')
    updated_at = models.DateField(auto_now=True,
                                  help_text='The date and time this review is updated')

    class Meta:
        verbose_name_plural = 'reviews'
        ordering = ['author']
    
    def __str__(self):
        return f"{self.author.email}'s thoughts on {self.product.name}"

eCommerce/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field is required')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

eCommerce/home/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Message', 'rows': 4}),
        }

eCommerce/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser
from django.contrib.auth import get_user_model

class RegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ['email', 'password1', 'password2']
    
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        
        # Placeholder values for different fields
        self.fields['email'].widget = forms.TextInput(attrs={'placeholder': 'Email'})
        self.fields['password1'].widget = forms.PasswordInput(attrs={'placeholder': 'Password'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'placeholder': 'Confirm Password'})

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget = forms.TextInput(attrs={'placeholder': 'Username'})
        self.fields['password'].widget = forms.PasswordInput(attrs={'placeholder': 'Password'})

eCommerce/home/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.contrib import messages

# Create your views here.
def index(request):
    return render(request, 'home/index.html')

def about(request):
    return render(request, 'home/about-us.html')

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()  # This saves the form data to the database
            messages.success(request, "The Contact form has been submitted successfully.")
            return redirect('home:contact')
    else:
        form = ContactForm()

    return render(request, 'home/contact.html', {'form': form})

eCommerce/products/views.py
from django.shortcuts import render

# Create your views here.

eCommerce/users/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm, LoginForm
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.views import View
from django.contrib import messages
from products.models import Product

# Create your views here.
def index(request):
    products = Product.objects.all()
    context = {
        "products": products
    }
    return render(request, 'users/homepage.html', context)

class registration(View):
    def get(self, request):
        return render(request, 'users/signup.html', {'form': RegistrationForm()})

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "User account created successfully! Please log in.")
            return redirect('users:login')
            # return render(request, 'users/signup.html', {'form': RegistrationForm()})
            # return HttpResponseRedirect(reverse_lazy('login'))  # Redirect to login page after successful signup
        else:
            return render(request, 'users/signup.html', {'form': form})
        return render(request, 'users/signup.html', {'form': form}) # displays any error messages, if any

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            print("form is valid")
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('users:home')
            else:
                form.add_error(None, 'Username or password is incorrect. Please try again')
        return render(request, 'users/login.html', {'form': form}) # display error messages
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('users:login')

eCommerce/templates/users/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="home.css">
    <title>E-Commerce Website</title>
</head>
<body>
    <!-- Header -->
    <nav class="navbar">
        <div class="nav">
            <img src="img/dark-logo.png" class="brand-logo" alt="">
            <div class="nav-items">
                <div class="search">
                    <input type="text" class="search-box" placeholder="Search brand, product">
                    <button class="search-btn">Search</button>
                </div>
            </div>
        </div>
    </nav>

    <!-- Main Content Goes Here -->

    <!-- Footer -->
    <footer class="footer">
        <!-- Footer content here -->
    </footer>
</body>
</html>

eCommerce/templates/users/homepage.html
{% extends 'home/index.html' %}
{% load static %}

{% block content %}
    <main class="main">
        <section class="product-tabs section-padding position-relative">
            <div class="container">
                <div class="section-title style-2 wow animate__animated animate__fadeIn">
                    <h3>Popular Products</h3>
                </div>
                <!--End nav-tabs-->
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="tab-one" role="tabpanel" aria-labelledby="tab-one">
                        <div class="row product-grid-4">
                            <!--end product card-->
                            {% for prod in products %}
                            <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
                                <div class="product-cart-wrap mb-30 wow animate__animated animate__fadeIn" data-wow-delay=".2s">
                                    <div class="product-img-action-wrap">
                                        <div class="product-img product-img-zoom">
                                            <a href="shop-product-right.html">
                                                {% comment %} <img class="default-img" src="{% static 'assets/imgs/shop/product-solar-1-1.png' %}" alt="" /> {% endcomment %}
                                                <img class="default-img" src="{{ prod.image.url }}" alt="" />
                                                <img class="hover-img" src="{% static 'assets/imgs/shop/product-solar-1-2.png' %}" alt="" />
                                            </a>
                                        </div>
                                    </div>
                                    <div class="product-content-wrap">
                                        <h2><a href="shop-product-right.html">{{ prod.name }}</a></h2>
                                        <div class="product-card-bottom">
                                            <div class="product-price">
                                                <span>{{ prod.price }}</span><br>
                                                <span>Product ID: {{ prod.id }}</span>
                                            </div>
                                            {% if not user.is_authenticated %}
                                            <div class="add-cart">
                                                <a class="add" href="{% url 'users:login' %}"><i class="fi-rs-shopping-cart mr-5"></i>Please Login </a>
                                            </div>
                                            {% else %}
                                            <div class="add-cart">
                                                <a class="add" href="{% url 'cart:add_to_cart' prod.id %}"><i class="fi-rs-shopping-cart mr-5"></i>Add </a>
                                            </div>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <!--End product-grid-4-->
                    </div>
                    <!--En tab one-->
                    <div class="tab-pane fade" id="tab-four" role="tabpanel" aria-labelledby="tab-four">
                        <div class="row product-grid-4">
                            <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
                                <div class="product-cart-wrap mb-30">
                                    <div class="product-img-action-wrap">
                                        <div class="product-img product-img-zoom">
                                            <a href="shop-product-right.html">
                                                <img class="default-img" src="{% static 'assets/imgs/shop/product-battery-1.png' %}" alt="" />
                                            </a>
                                        </div>
                                    </div>
                                    <div class="product-content-wrap">
                                        <h2><a href="shop-product-right.html">Solar Battery</a></h2>
                                        <div class="product-rate-cover">
                                            <div class="product-rate d-inline-block">
                                                <div class="product-rating" style="width: 90%"></div>
                                            </div>
                                            <span class="font-small ml-5 text-muted"> (4.0)</span>
                                        </div>
                                        <div class="product-card-bottom">
                                            <div class="product-price">
                                                <span>£28.85</span>
                                            </div>
                                            <div class="add-cart">
                                                <a class="add" href="usercart.html"><i class="fi-rs-shopping-cart mr-5"></i>Add </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock content %}

eCommerce/templates/users/index.html
{% extends 'home/index.html' %}

{% block title %}Sign In Page{% endblock %}

{% block content %}

<div class="home-container">
    <div class="form login">
      <h1>Welcome</h1>
      {% if request.user.is_authenticated %}
        <p>{{ request.user.email }}</p>
        <a href="{% url 'users:logout' %}">Logout</a>
      {% else %}
        <a href="{% url 'users:login' %}">Login</a>
        <a href="{% url 'users:register' %}">Signup</a>
      {% endif %}
      </div>
    </div>
  </div>

{% comment %} <h1>Welcome!</h1>

{% if request.user.is_authenticated %}
  <p>{{ request.user.email }}</p>
  <a href="{% url 'users:logout' %}">Logout</a>
{% else %}
  <a href="{% url 'users:login' %}">Login</a>
  <a href="{% url 'users:register' %}">Signup</a>
{% endif %} {% endcomment %}

{% endblock content %}

eCommerce/templates/users/login.html
{% extends 'home/index.html' %}
    
{% block content %}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> Log In
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <div class="heading_s1">
                                            <h1 class="mb-5">Log In</h1>
                                            <p class="mb-30">Don't have an account? <a href="{% url 'users:register' %}">Sign Up</a></p>
                                        </div>
                                        <form method="POST" action="{% url 'users:login' %}">
                                            {% csrf_token %}

                                            {% comment %} Displaying any authentication errors {% endcomment %}
                                            {% if form.non_field_errors %}
                                                <div class="errors">
                                                {% for error in form.non_field_errors %}
                                                    <p class="error">{{ error }}</p>
                                                {% endfor %}
                                                </div>
                                            {% endif %}

                                            {{ form.username }}
                                            {% if form.username.errors %}
                                                {% for error in form.username.errors %}
                                                    <div class="error">{{ error }}</div>
                                                {% endfor %}
                                            {% endif %}

                                            {{ form.password }}
                                            {% if form.password.errors %}
                                                {% for error in form.password.errors %}
                                                    <div class="error">{{ error }}</div>
                                                {% endfor %}
                                            {% endif %}
                                            <input type="submit" class="button" value="Login">
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

eCommerce/templates/users/signin.html
{% extends 'home/index.html' %}

{%load static%}
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock %}

{% block title %}Sign In Page{% endblock %}

{% block content %}
  <div class="container">
    <div class="form login">
      <header>Login</header>
      <form method="POST" action="{% url 'users:login' %}">
        {% csrf_token %}

        {% comment %} Displaying any authentication errors {% endcomment %}
        {% if form.non_field_errors %}
            <div class="errors">
              {% for error in form.non_field_errors %}
                <p class="error">{{ error }}</p>
              {% endfor %}
            </div>
        {% endif %}

        {{ form.username }}
        {% if form.username.errors %}
            {% for error in form.username.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}
        {% endif %}

        {{ form.password }}
        {% if form.password.errors %}
            {% for error in form.password.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}
        {% endif %}
        <input type="submit" class="button" value="Login">
      </form>
      <div class="signup">
        <span>Don't have an account?
         <a href="{% url 'users:register' %}">Signup</a>
        </span>
      </div>
    </div>
  </div>
{% endblock content %}

eCommerce/templates/users/signup.html
{% extends 'home/index.html' %}
{% load static %}

{% block content %}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> Create An Account
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <div class="heading_s1">
                                            <h1 class="mb-5">Create an Account</h1>
                                            <p class="mb-30">Already have an account? <a href="{% url 'users:login' %}">Login</a></p>
                                        </div>
                                        {% comment %} <form method="post">
                                            <div class="form-group">
                                                <input type="text" required="" name="username" placeholder="Username" />
                                            </div>
                                            <div class="form-group">
                                                <input type="text" required="" name="email" placeholder="Email" />
                                            </div>
                                            <div class="form-group">
                                                <input required="" type="password" name="password" placeholder="Password" />
                                            </div>
                                            <div class="form-group">
                                                <input required="" type="password" name="password" placeholder="Confirm password" />
                                            </div>
                                           
                                            <div class="login_footer form-group mb-50">
                                                <div class="chek-form">
                                                    <div class="custome-checkbox">
                                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox12" value="" />
                                                        <label class="form-check-label" for="exampleCheckbox12"><span>I agree to terms &amp; Policy.</span></label>
                                                    </div>
                                                </div>
                                                <a href="page-privacy-policy.html"><i class="fi-rs-book-alt mr-5 text-muted"></i>Lean more</a>
                                            </div>
                                            <div class="form-group mb-30">
                                                <button type="submit" class="btn btn-fill-out btn-block hover-up font-weight-bold" name="login">Sign Up</button>
                                            </div>
                                            <!-- <p class="font-xs text-muted"><strong>Note:</strong>Your personal data will be used to support your experience throughout this website, to manage access to your account, and for other purposes described in our privacy policy</p> -->
                                        </form> {% endcomment %}
                                        <form method="POST" action="{% url 'users:register' %}">
                                            {% csrf_token %}
                                            {{ form.email }}
                                            {% if form.email.errors %}
                                                {% for error in form.email.errors %}
                                                    <div class="error">{{ error }}</div>
                                                {% endfor %}
                                            {% endif %}
                                            {{ form.password1 }}
                                            {% if form.password1.errors %}
                                                {% for error in form.password1.errors %}
                                                    <div class="error">{{ error }}</div>
                                                {% endfor %}
                                            {% endif %}
                                            {{ form.password2 }}
                                            {% if form.password2.errors %}
                                                {% for error in form.password2.errors %}
                                                    <div class="error">{{ error }}</div>
                                                {% endfor %}
                                            {% endif %}
                                            <input type="submit" class="button" value="Register">
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}    