eCommerce/cart/urls.py
from django.urls import path
from cart import views

app_name = "cart"

urlpatterns = [
    path('', views.cart, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('change/<int:item_id>/', views.change_item_quantity, name='change_item_quantity'),

    path('confirm-order/', views.confirm_order, name='confirm_order'),
    path('order-confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
]

eCommerce/eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls')),
    path("users/", include("users.urls")),
    path("cart/", include("cart.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eCommerce/cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from products.models import Product
import uuid

User = get_user_model()

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True)

    def save(self, *args, **kwargs):
        if not self.unit_price:
            self.unit_price = self.product.price
        super(CartItem, self).save(*args, **kwargs)
    
    def subtotal(self):
        return self.quantity * self.unit_price
    
    def __str__(self):
        return f"Cart Item: {self.product.name}"

# Order Management
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    order_number = models.CharField(max_length=30, unique=True, editable=False)

    # creating a unique order number
    def save(self, *args, **kwargs):
        if not self.order_number:
            self.order_number = self.generate_order_number()
        super().save(*args, **kwargs)

    def generate_order_number(self):
        return f"SS-OrderID-{int(self.created_at.timestamp())}"
    
    def get_total_cost(self):
        return sum(item.quantity * item.price for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def subtotal(self):
        return self.quantity * self.price

eCommerce/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cart, CartItem, Order, OrderItem
from products.models import Product
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.utils import timezone
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.views import View
from django.contrib import messages


@login_required
def cart(request):
    cart, created = Cart.objects.get_or_create(user=request.user, defaults={'created_at': datetime.now()})
    items = cart.items.all()
    total = sum(item.quantity * item.unit_price for item in items)
    context = {
        'cart': cart,
        'total': total
    }
    return render(request, 'cart/usercart.html', context)

@login_required
def cart_detail(request):
    cart, created = Cart.objects.get_or_create(user=request.user, defaults={'created_at': datetime.now()})
    return render(request, 'cart/usercart.html', {'cart': cart})

@login_required
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product, defaults={'unit_price': product.price})
    if not created:
        cart_item.quantity += 1
        cart_item.save()
    return redirect('cart:cart_detail')

@login_required
def remove_from_cart(request, item_id):
    cart_item = get_object_or_404(CartItem, id=item_id, cart__user=request.user)
    cart_item.delete()
    return redirect('cart:cart_detail')

@login_required
def change_item_quantity(request, item_id):
    if request.method == 'POST':
        quantity = int(request.POST.get('quantity', 1))
        cart_item = get_object_or_404(CartItem, id=item_id, cart__user=request.user)
        if quantity > 0:
            cart_item.quantity = quantity
            cart_item.save()
        else:
            cart_item.delete()
        return redirect('cart:cart_detail')
    return redirect('cart:cart_detail')

@login_required
def confirm_order(request):
    if request.method == 'POST':
        cart = Cart.objects.get(user=request.user)
        order = Order.objects.create(user=request.user, created_at=timezone.now())
        
        for item in cart.items.all():
            OrderItem.objects.create(
                order=order,
                product=item.product,
                quantity=item.quantity,
                price=item.product.price
            )
        
        context = {
            'order': order,
        }
        
        cart.items.all().delete()
        return render(request, 'cart/order-confirmation.html', context)


    return render(request, 'cart/checkout.html')

def order_confirmation(request, order_id):
    order = Order.objects.get(id=order_id)
    return render(request, 'cart/order-confirmation.html', {'order': order})

eCommerce/templates/cart/cart_detail.html
{% extends 'home/index.html' %}
{% load static %}

{% block content %}
<h1>Your Cart</h1>
    {% if cart.items.all %}
        <ul>
        {% for item in cart.items.all %}
            <li>
                {{ item.product.name }} - 
                <form action="{% url 'cart:change_item_quantity' item.id %}" method="post">
                    {% csrf_token %}
                    <input type="number" name="quantity" value="{{ item.quantity }}" min="1" style="width: 50px;">
                    x £{{ item.unit_price }} = £{{ item.subtotal }}
                    <button type="submit">Update</button>
                </form>
                <a href="{% url 'cart:remove_from_cart' item.id %}">Remove</a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Your cart is empty.</p>
    {% endif %}
{% endblock content %}

eCommerce/templates/cart/order-confirmation.html
{% extends 'home/index.html' %}
{% load static %}

{% block content %}
    <body>
        <div class="invoice invoice-content invoice-5">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="invoice-inner">
                            <div class="invoice-info" id="invoice_wrapper">
                                <div class="invoice-header">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="logo d-flex align-items-center">
                                                <a href="index.html" class="mr-20"><img src="{% static 'assets/imgs/theme/surrey-logo.png' %}" alt="logo" /></a>
                                                <div class="text">
                                                    <strong class="text-brand">SurreySolars Ltd</strong> <br />
                                                    University of Surrey, Guildford GU2 7XH
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6 text-end">
                                            <h2>INVOICE</h2>
                                            <h6>DATE: {{ order.created_at }} </h6>
                                            <h6>Order ID: <span class="text-brand">{{ order.order_number }}</span></h6>
                                        </div>
                                    </div>
                                </div>
                                <div class="invoice-banner">
                                    {% comment %} <img src="{% static 'assets/imgs/banner/banner20.jpg' %}" alt=""> {% endcomment %}
                                    <h4>Thank you for your order with following details:</h4>
                                </div>
                                <div class="invoice-center">
                                    <div class="table-responsive">
                                        <table class="table table-striped invoice-table">
                                            <thead class="bg-active">
                                                <tr>
                                                    <th>Title</th>
                                                    <th class="text-center">Price</th>
                                                    <th class="text-center">Quantity</th>
                                                    <th class="text-right">Amount</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            {% for item in order.items.all %}
                                                <tr>
                                                    <td>
                                                        <div class="item-desc-1">
                                                            <span>{{ item.product.name }}</span>
                                                            <small>SKU: {{ item.product.sku }}</small>
                                                        </div>
                                                    </td>
                                                    <td class="text-center">£{{ item.price }}</td>
                                                    <td class="text-center">{{ item.quantity }}</td>
                                                    <td class="text-right">£{{ item.subtotal }}</td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="invoice-bottom pb-80">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <h6 class="mb-15">Details of the Order</h6>
                                            <p class="font-sm">
                                                <strong>Order creation date:</strong> {{ order.created_at }} <br />
                                                <strong>Invoice To:</strong> {{ order.user }} <br />
                                                <strong>Order Tracking Number:</strong> {{ order.order_number }}
                                            </p>
                                        </div>
                                        <div class="col-md-6 text-end">
                                            <h6 class="mb-15">Total Amount</h6>
                                            <h3 class="mt-0 mb-0 text-brand">£{{ order.get_total_cost }}</h3>
                                            <p class="mb-0 text-muted">Taxes Included</p>
                                        </div>
                                    </div>
                                    <div class="row text-center">
                                        <div class="hr mt-30 mb-30"></div>
                                        <p class="mb-0 text-muted"><strong>Note:</strong>This is computer generated receipt and does not require physical signature.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="invoice-btn-section clearfix d-print-none">
                                <a href="javascript:window.print()" class="btn btn-lg btn-custom btn-print hover-up"> <img src="{% static 'assets/imgs/theme/icons/icon-print.svg' %}" alt="" /> Print </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
{% endblock content %}

eCommerce/templates/cart/usercart.html
{% extends 'home/index.html' %}
{% load static %}

{% block content %}
    <main class="main">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Cart
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Your Cart</h1>
                    <div class="d-flex justify-content-between">
                        <h6 class="text-body">You have a total of <span class="text-brand">{{ cart.items.all.count }}</span> products in your cart</h6>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8">
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    <th class="custome-checkbox start pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="">
                                        <label class="form-check-label" for="exampleCheckbox11"></label>
                                    </th>
                                    <th scope="col" colspan="2">Product</th>
                                    <th scope="col">Unit Price</th>
                                    <th scope="col">Quantity</th>
                                    <th scope="col">Subtotal</th>
                                    <th scope="col" class="end">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if cart.items.all %}
                                    <ul>
                                    {% for item in cart.items.all %} 
                                        <tr class="pt-30">
                                            <td class="custome-checkbox pl-30">
                                                <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="">
                                                <label class="form-check-label" for="exampleCheckbox1"></label>
                                            </td>
                                            <td class="image product-thumbnail pt-40"><img src="{{ item.product.image.url }}" alt="#"></td>
                                            <td class="product-des product-name">
                                                <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="shop-product-right.html">{{ item.product.name }}</a></h6>
                                            </td>
                                            <td class="price" data-title="Price">
                                                <h4 class="text-body"> £ {{ item.unit_price }} </h4>
                                            </td>
                                            <td class="text-center detail-info" data-title="Stock">
                                                <form action="{% url 'cart:change_item_quantity' item.id %}" method="post">
                                                    {% csrf_token %}
                                                    <input type="number" name="quantity" value="{{ item.quantity }}" min="1" style="width: 50px;">
                                                    <button type="submit">Update</button>
                                                </form>
                                            </td>
                                            <td class="price" data-title="Price">
                                                <h4 class="text-brand">£ {{item.subtotal}} </h4>
                                            </td>
                                            <td class="action text-center" data-title="Remove"><a href="{% url 'cart:remove_from_cart' item.id %}" class="text-body"><i class="fi-rs-trash"></i></a></td>
                                        </tr>
                                    {% endfor %}
                                    </ul>
                                {% else %}
                                    <p>Your cart is empty.</p>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="border p-md-4 cart-totals ml-30">
                        <div class="table-responsive">
                            <table class="table no-border">
                                <tbody>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Subtotal</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 class="text-brand text-end">£{{ total }}</h4>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td scope="col" colspan="2">
                                            <div class="divider-2 mt-10 mb-10"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Shipping</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h5 class="text-heading text-end">Free</h4></td> </tr> <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Estimate for</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h5 class="text-heading text-end">United Kingdom</h4></td> </tr> <tr>
                                        <td scope="col" colspan="2">
                                            <div class="divider-2 mt-10 mb-10"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Total</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 class="text-brand text-end">£{{ total }}</h4>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        
                        <div class="payment ml-30">
                            <h4 class="mb-30">Payment</h4>
                            <div class="payment_option">
                                <!-- <div class="custome-radio">
                                    <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios3" checked="">
                                    <label class="form-check-label" for="exampleRadios3" data-bs-toggle="collapse" data-target="#bankTranfer" aria-controls="bankTranfer">Direct Bank Transfer</label>
                                </div> -->
                                <div class="custome-radio">
                                    <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios4" checked="">
                                    <label class="form-check-label" for="exampleRadios4" data-bs-toggle="collapse" data-target="#checkPayment" aria-controls="checkPayment">Cash on delivery</label>
                                </div>
                            </div>
                            <div class="payment-logo d-flex">
                                <img class="mr-15" src="assets/imgs/theme/icons/payment-paypal.svg" alt="">
                                <img class="mr-15" src="assets/imgs/theme/icons/payment-visa.svg" alt="">
                                <img class="mr-15" src="assets/imgs/theme/icons/payment-master.svg" alt="">
                                <img src="assets/imgs/theme/icons/payment-zapper.svg" alt="">
                            </div>
                        </div>
                        <form method="post" action="{% url 'cart:confirm_order' %}">
                            {% csrf_token %}
                            <button type="submit">Confirm Order</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}